apiVersion: v1
kind: Service
metadata:
  name: eureka-hello
spec:
  selector:
    app: eureka-hello
  type: NodePort
  ports:
    - port: {{ .Values.app.demo_port}}
      targetPort: {{ .Values.app.demo_port}}
      protocol: TCP
      name: tcp
      nodePort: {{ .Values.service.nodePort }}
