apiVersion: v1
kind: Service
metadata:
  name: eureka-demo
spec:
  selector:
    app: eureka-demo
  type: NodePort
  ports:
    - port: 8761
      targetPort: 8761
      protocol: TCP
      name: tcp
      nodePort: {{ .Values.service.nodePort }}
